x_pos_bound: [-450,50.0]
y_pos_bound: [300.0,400.0]
x_vel_bound: [0.0,10.0]   
y_vel_bound: [-10.0,20.0]
avoid_weight: 0.02
vel_weight: 0.125
avoid_radius: 10
vel_radius: 100
x_lim: [-500,1500]
y_lim: [-500,1500]
no_boids: 50
    